TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false
  
  # Forward Simulation Parameters
  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 20
  vtheta_samples: 40
  
  # Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: world

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1