footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
transform_tolerance: 0.5
map_type: costmap

obstacle_layer:
  enabled: true
  obstacle_range: 5.0
  raytrace_range: 7.0
  inflation_radius: 0.3
  track_unknown_space: false
  combination_method: 1
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.5

static_layer:
  enabled: true
  map_topic: "/map"